<%= "\n"*30 %>
<%= "# YOU ARE IN THE WRONG PLACE" %>
<%= "# YOU ARE IN THE WRONG PLACE use the ERB file" %>
<%= "# YOU ARE IN THE WRONG PLACE" %>

FROM docker.io/library/python:3.9

RUN apt-get update && apt-get install -y default-jre-headless vim flex bison

# Download and install jbofihe
RUN cd /tmp ; wget https://github.com/lojban/jbofihe/archive/v0.44.tar.gz ; tar -zxvf v0.44.tar.gz

RUN cd /tmp/jbofihe-0.44 ; perl config.pl --prefix=/usr/local
RUN cd /tmp/jbofihe-0.44 ; make all
RUN cd /tmp/jbofihe-0.44 ; make install

# Download and install all the python bits
RUN pip install --upgrade pip
RUN pip install Flask~=2.0 gunicorn

WORKDIR /src
